### ISSUE TITLE
npm ERR! 404

### ISSUE THREAD

**Issue by hems** [shyal/meteor-station#5]
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/meteor-station

**Comment by shyal** [comment]
I'm confused. Can you be more specific with this issue? What is it about?

**Comment by hems** [comment]
````
~/tmp [ npm install meteor-station                                                                                                                                                                                                                      ] 2:59 PM
npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/h/.nvm/versions/node/v5.12.0/bin/node" "/Users/h/.nvm/versions/node/v5.12.0/bin/npm" "install" "meteor-station"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/meteor-station
npm ERR! 404
npm ERR! 404  'meteor-station' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/h/tmp/npm-debug.log
````

**Comment by shyal** [comment]
Right. Yes sorry it's not on NPM yet. Please clone the repo and install from the clone. Please let me know how you get on.

**Comment by hems** [comment]
You just need to run npm publish !? Why you still didn't do it? ( :

**Comment by hems** [comment]
even before putting instructions on the readme file!

**Comment by shyal** [comment]
I'd like meteor-station to be a little more used / tested / stable before doing so. Currently I'm the only user.

**Comment by hems** [comment]
it looks cool! i like coffee as well 👍 

unfortunately i have no time to test it..end up solving my own issue ( mupx stoped working over fibers error ) using rsync + shell..

peace

**Comment by shyal** [comment]
No issues at all. if you ever totally give up on mupx and want to give
meteor-station a shot then let me know
